version: "3.8"

services:
  blog-api:
    build: .
    container_name: blog-api
    ports:
      - "3000:3000"
    volumes:
      - blog-db-data:/app/db
    env_file:
      - .env
    restart: unless-stopped

volumes:
  blog-db-data:
    driver: local
